### ISSUE TITLE
Can't use S3Event as Lambda[S3Event, Any]

### ISSUE THREAD

**Issue by Jay-JS** [mkotsur/aws-lambda-scala#20]
Hey,
Throws compilation errors while using 
`class S3EventHandler extends Lambda[S3Event,String]`

Error Message : 
` could not find implicit value for evidence parameter of type io.github.mkotsur.aws.handler.CanDecode[com.amazonaws.services.lambda.runtime.events.S3Event]`

**Comment by mkotsur** [comment]
Hi @Jay-JS. That's true, there are no encoders/decoders for the S3Event Java class, and since it's not an ADT, the automatic decoding doesn't work. You have at least two possibilities:

1. Create a case class, which describes the event payload. E.g.:

```scala
  import io.circe.generic.auto._
  import io.github.mkotsur.aws.handler.Lambda._
  import io.github.mkotsur.aws.handler.Lambda

  object MyS3Event {
    case class S3Bucket(name: String)
    case class S3Object(key: String)
    case class S3Attributes(bucket:S3Bucket, `object`: S3Object)
    case class Record(eventVersion: String, s3: S3Attributes)
  }
  case class MyS3Event(Records: MyS3Event.Record)

  class S3EventHandler extends Lambda[MyS3Event,String] {
      ???
  }
```

You have to cover only the fields that you need.

2. If you are a bit familiar with [circe](https://github.com/circe/circe), and specifically with the [optics](https://circe.github.io/circe/optics.html) module, just say that the input is a `Json`, and then extract all necessary information using optics (or cursors):

```scala
  class S3EventHandler extends Lambda[Json,String] {
    override protected def handle(i: Json, c: Context): Either[Throwable, String] = {
      super.handle(i, c)

      import io.circe.optics.JsonPath._
      val _keys = root.Records.each.s3.`object`.key.string
      val keys: List[String] = _keys.getAll(i)
      
      ???
    }
  }
```

I've used [this document](https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html) to find the structure of the event, so if it's different in your case, the field names should be changed. The code is for illustration purposes and not tested, although there is a high chance that it'll work :-)

**Comment by Jay-JS** [comment]
Thanks @mkotsur. It makes sense to me as It's not an ADT, supplying default encoder/decoder implicits won't be much useful for longer. Your code snippets look fine and useful. Don't you feel adding similar details to the readme can save sometime for others. It becomes little bit tricky as java-aws-lambda supports encoding/decoding for different aws events.
