### ISSUE TITLE
Build and release a version for 2.13

### ISSUE THREAD

**Issue by mkotsur** [mkotsur/aws-lambda-scala#21]

**Comment by plokhotnyuk** [comment]
You have choices:
- drop support of Scala 2.11 (because circe maintainers dropped it for versions that available for Scala 2.13)
- duplicate code-base in different directories to continue Scala 2.11 support

Also, please, consider an option to use other JSON parsers (like [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala)) which support Scala 2.11/2.12/2.13
